---
- name: Create a user with given variables
  hosts: localhost
  become: yes
  remote_user: ansible
  become_user: root
  vars_files:
   - vars/pass.yml
  tasks:
   - name: Create
     user:
      name: rockey 
      password: "{{password|password_hash('sha512')}}"
      update_password: on_create
      state: present
...
